name: 4i
favicon: null
layout_spectrum: 0.49662
typography_spectrum: 0.4954
title: Beta Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9eaee'
    - '#4d67a0'
    - '#004b1c'
    - '#f90102'
    - '#00affb'
  brandStrength: 0.5
  lightness: 0.21566538466140628
  saturation: 0.3302808851003647
  rhythmicContrast: 0.6038902823347598
purpose: []
